export const HeaderHeight = 76
export const DrawerWidth = 250
export const CartWidth = 360
export const FilterBarHeight = 80
export const MenuUrls = ['/', '/results', '/nfters', '/profile/nfts', '/profile/orders', '/profile/favorites']
export const PageSizeInGallery=9
export const BatchSizeInGallery=30
export const PageSizeInComments=3
export const MaxValueInFilter = 1000
export const MinValueInFilter = 0
export const SYSSYMBOL = 'CH'