export const HeaderHeight = 76
export const DrawerWidth = 250
export const CartWidth = 360
export const FilterBarHeight = 80
export const MenuUrls = ['/', '/results', '/nfters', '/profile/nfts', '/profile/orders', '/profile/favorites']
export const PageSizeInGallery=100
export const BatchSizeInGallery=30
export const PageSizeInComments=3
export const CATEGORIES = ['pets', 'clothes', 'cosmetics', 'outfits', 'car', 'devices', 'books']
export const MaxValueInFilter = 100
export const MinValueInFilter = 0
export const NFTSTATUS = ['on', 'off']
export const SYSSYMBOL = 'CH'