export const BACKEND_ADDR = "http://localhost:3100"
export const HeaderHeight = 76
export const DrawerWidth = 250
export const CartWidth = 360
export const FilterBarHeight = 80
export const MenuUrls = ['/', '/results', '/nfters', '/profile/nfts', '/profile/orders', '/profile/favorites']
export const PageSizeInGallery=100
export const BatchSizeInGallery=30
export const NETWORKS = ['ethereum', 'polygon', 'avalanche', 'solana']